//
//  Copyright (c) 2013-2015 Next Audio Labs, LLC. All rights reserved.
//
//  This file contains confidential and proprietary information of Next
//  Audio Labs, LLC ("Next"). No use is permitted without express written
//  permission of Next. If you are not a party to a Confidentiality/
//  Non-Disclosure Agreement with Next, please immediately delete this
//  file as well as all copies in your possession. For further information,
//  please email info@nextaudiolabs.com.
//

#pragma mark Public Interface

/*! Warning generated by some operation. */
@interface NxAWarning : NSObject <NSCopying>

#pragma mark Factory Methods

/*!
 * Creates an NxAWarning using specific attributes.
 * \param description A description of the error.
 * \return An NxAWarning with the given description.
 */
+ (instancetype)warningWithDescription:(NSString *)description;

/*!
 * Creates an NxAWarning using specific attributes.
 * \param description A description of the warning.
 * \param url A URL which links to additional information about the warning.
 * \return An NxAWarning with the given attributes.
 */
+ (instancetype)warningWithDescription:(NSString *)description
                         additionalUrl:(NSString *)url;

#pragma mark Properties

/*! URL which links to additional information about this warning. */
@property (readonly, nonatomic) NSString *additionalUrl;

@end
